"""create user_profiles table

Revision ID: d75b0ced6164
Revises: 
Create Date: 2026-07-26 21:54:09.684625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75b0ced6164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=300), nullable=True),
    sa.Column('biography', sa.String(length=750), nullable=True),
    sa.Column('budget_limit', sa.Integer(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('visibility_choice', sa.Enum('PRIVATE', 'LINK', 'PUBLIC', name='visibilitychoice'), nullable=False),
    sa.Column('monthly_budget_exceeded_notification', sa.Boolean(), nullable=False),
    sa.Column('weekly_summary_notification', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
