"""add user_budget table

Revision ID: d6d7b8b546ac
Revises: 7771a91a3596
Create Date: 2026-07-24 02:51:11.356195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d7b8b546ac'
down_revision: Union[str, Sequence[str], None] = '7771a91a3596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budget',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('budget_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_budget')
    # ### end Alembic commands ###
