"""create user_contacts, notification_settings and notification_logs tables

Revision ID: 09c19ab249dd
Revises: 
Create Date: 2026-07-26 21:51:16.779827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c19ab249dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notifications_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_topic', sa.String(length=200), nullable=False),
    sa.Column('notification_message', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_contacts.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_exceeded_notification', sa.Boolean(), nullable=False),
    sa.Column('weekly_summary_notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_contacts.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_settings')
    op.drop_table('notifications_logs')
    op.drop_table('user_contacts')
    # ### end Alembic commands ###
