"""remove fk notification log to preserve user id after deletion

Revision ID: 6c8208eb876b
Revises: 09c19ab249dd
Create Date: 2026-08-06 03:14:29.417141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8208eb876b'
down_revision: Union[str, Sequence[str], None] = '09c19ab249dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_logs_user_id_fkey'), 'notifications_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('notifications_logs_user_id_fkey'), 'notifications_logs', 'user_contacts', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
