"""create transactions table

Revision ID: e12d063a3a3c
Revises: 
Create Date: 2026-07-09 13:26:48.690486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12d063a3a3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('EXPENSE', 'INCOME', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('SUBSCRIPTIONS', 'INVESTMENTS', 'TAXES', 'TRAVEL', 'HOBBY', 'GIFTS', 'CLOTHES', 'HOUSEHOLD', 'INSURANCE', 'PERSONAL_CARE', 'TRANSPORT', 'SPORT', 'ENTERTAINMENT', 'PRODUCTS', 'SALARY', 'TRANSFERS', 'RESTAURANT', 'CREDIT', 'DEBTS', 'OTHER', 'PETS', 'HEALTHCARE', 'REFUND', name='categories'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
